### PR TITLE
Added requirements.txt file

### PR DESCRIPTION
**Pull request by HariNithyaRao**
The file consists of necessary libraries to be installed before running the script.
Please once check it.

### CODE REVIEW

**Comment by Evildricks** [comment]
@HariNithyaRao just add some screenshots of the working of the project. I will merge it immediately

**Comment by HariNithyaRao** [comment]
Please refer this issue I have added the video recording.
https://github.com/Evildricks/Weather_App_Python/issues/3#issuecomment-1783822741

**Comment by Evildricks** [comment]
@HariNithyaRao Great Job

**Comment by HariNithyaRao** [comment]
Thank you @Evildricks .

**Comment by HariNithyaRao** [comment]
I would like to update the readme as well .

**Comment by PranavBarthwal** [comment]
@HariNithyaRao 
Screenshot (56)
how can I run this on my local system?

**Comment by Evildricks** [comment]
@HariNithyaRao for sure  ,please do it

**Comment by HariNithyaRao** [comment]
@PranavBarthwal run the script using the below command in terminal:

streamlit run main.py

I have included the command to run the script in the comments of the main.py script as well.

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal run the script using the below command in terminal:
> 
> streamlit run main.py
> 
> I have included the command to run the script in the comments of the main.py script as well.

check my attatched screenshot, streamlit run main.py command is giving error.

I have installed all the necessary packages.

**Comment by HariNithyaRao** [comment]
@PranavBarthwal pls change your path to Weather_App_Python directory and then run the command.

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal pls change your path to Weather_App_Python directory and then run the command.
> 

Thanks.

**Comment by HariNithyaRao** [comment]
> @HariNithyaRao for sure ,please do it

@Evildricks i have updated the readme file. Please check

**Comment by Evildricks** [comment]
@HariNithyaRao Great Work!!!

**Pull request merged**
